from ...models import Category

smart_phone = Category.objects.get(name='SmartPhone')

# sub-categories of SmartPhone
android = Category.objects.create(name='Android', parent=smart_phone)
iphone = Category.objects.create(name='iPhone', parent=smart_phone)

# sub-categories of Android
tecno = Category.objects.create(name='Tecno', parent=android)
itel = Category.objects.create(name='Itel', parent=android)
samsung = Category.objects.create(name='Samsung', parent=android)
huawei = Category.objects.create(name='Huawei', parent=android)
xiaomi = Category.objects.create(name='Xiaomi', parent=android)
oppo = Category.objects.create(name='Oppo', parent=android)
google_pixel = Category.objects.create(name='Google Pixel', parent=android)
vivo = Category.objects.create(name='Vivo', parent=android)
motorola = Category.objects.create(name='Motorola', parent=android)
sony = Category.objects.create(name='Sony', parent=android)
nokia = Category.objects.create(name='Nokia', parent=android)
lg = Category.objects.create(name='LG', parent=android)
asus = Category.objects.create(name='Asus', parent=android)
lenovo = Category.objects.create(name='Lenovo', parent=android)
zte = Category.objects.create(name='ZTE', parent=android)
gionee = Category.objects.create(name='Gionee', parent=android)
infinix = Category.objects.create(name='Infinix', parent=android)
blackberry = Category.objects.create(name='Blackberry', parent=android)

# sub-categories of iPhone
iphone_6 = Category.objects.create(name='iPhone 6', parent=iphone)
iphone_7 = Category.objects.create(name='iPhone 7', parent=iphone)
iphone_8 = Category.objects.create(name='iPhone 8', parent=iphone)
iphone_X = Category.objects.create(name='iPhone X', parent=iphone)
iphone_xs = Category.objects.create(name='iPhone XS', parent=iphone)
iphone_xr = Category.objects.create(name='iPhone XR', parent=iphone)
iphone_11 = Category.objects.create(name='iPhone 11', parent=iphone)
iphone_12 = Category.objects.create(name='iPhone 12', parent=iphone)
iphone_13 = Category.objects.create(name='iPhone 13', parent=iphone)
iphone_14 = Category.objects.create(name='iPhone 14', parent=iphone)
iphone_15 = Category.objects.create(name='iPhone 15', parent=iphone)
iphone_13promax = Category.objects.create(name='iPhone 13 Pro Max', parent=iphone)
iphone_12promax = Category.objects.create(name='iPhone 12 Pro Max', parent=iphone)
iphone_11promax = Category.objects.create(name='iPhone 11 Pro Max', parent=iphone)
iphone_15pro = Category.objects.create(name='iPhone 15 Pro', parent=iphone)
iphone_15plus = Category.objects.create(name='iPhone 15 Plus', parent=iphone)
iphone_14promax = Category.objects.create(name='iPhone 14 Pro Max', parent=iphone)
iphone_15promax = Category.objects.create(name='iPhone 15 Pro Max', parent=iphone)
iphone_14plus = Category.objects.create(name='iPhone 14 Plus', parent=iphone)
iphone_13pro = Category.objects.create(name='iPhone 13 Pro', parent=iphone)
iphone_13mini = Category.objects.create(name='iPhone 13 Mini', parent=iphone)
iphone_12pro = Category.objects.create(name='iPhone 12 Pro', parent=iphone)
iphone_12mini = Category.objects.create(name='iPhone 12 Mini', parent=iphone)
iphone_11pro = Category.objects.create(name='iPhone 11 Pro', parent=iphone)
iphone_xsmax = Category.objects.create(name='iPhone XS Max', parent=iphone)
iphone_8plus = Category.objects.create(name='iPhone 8 Plus', parent=iphone)
iphone_7plus = Category.objects.create(name='iPhone 7 Plus', parent=iphone)
iphone_6splus= Category.objects.create(name='iPhone 6s Plus', parent=iphone)
iphone_6s = Category.objects.create(name='iPhone 6s', parent=iphone)
iphone_5s= Category.objects.create(name='iPhone 5s', parent=iphone)
iphone_5c = Category.objects.create(name='iPhone 5c', parent=iphone)
iphone_5 = Category.objects.create(name='iPhone 5', parent=iphone)
iphone_4s = Category.objects.create(name='iPhone 4s', parent=iphone)
iphone_4cdma = Category.objects.create(name='iPhone 4 CDMA', parent=iphone)
iphone_4 = Category.objects.create(name='iPhone 4', parent=iphone)
iphone_3g = Category.objects.create(name='iPhone 3G', parent=iphone)
iphone_3gs = Category.objects.create(name='iPhone 3GS', parent=iphone)
iphone_se = Category.objects.create(name='iPhone SE', parent=iphone)
iphone_se22 = Category.objects.create(name='iPhone SE(2020)', parent=iphone)
iphone_se22 = Category.objects.create(name='iPhone SE(2022)', parent=iphone)
