# Generated by Django 5.0.3 on 2024-05-13 17:05

import django.db.models.deletion
import django.utils.timezone
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=250)),
                ('lastname', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250, unique=True)),
                ('password', models.CharField(max_length=250)),
                ('session_id', models.CharField(max_length=250, null=True)),
                ('phone_no', models.BigIntegerField(default='012456520', null=True)),
                ('reset_token', models.CharField(max_length=250, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Category Name', max_length=100)),
                ('tree_id', models.CharField(default='tree-id', max_length=100)),
                ('level', models.PositiveIntegerField(default=0)),
                ('rght', models.PositiveIntegerField(default=1)),
                ('lft', models.PositiveIntegerField(default=1)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='backend.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='title', max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('negotiable', models.BooleanField(null=True)),
                ('image', models.ImageField(default='product_image.jpg', upload_to='Image/Image')),
                ('product_name', models.CharField(blank=True, max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='backend.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_id', to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(default='product_image.jpg', upload_to='Image/Image')),
                ('product', models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='backend.product')),
            ],
        ),
    ]
