# Generated by Django 4.2.11 on 2024-05-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Default Category Name', max_length=100, unique=True),
        ),
    ]
