# Generated by Django 4.2.11 on 2024-07-16 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppost',
            name='media',
        ),
        migrations.CreateModel(
            name='ShopPostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='shop_posts/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='backend.shoppost')),
            ],
        ),
    ]
