# Generated by Django 4.2.11 on 2024-07-21 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_subcategory_shopproduct_subcategory'),
    ]

    operations = [
        
    ]
