# Generated by Django 4.2.11 on 2024-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_productsuggestion_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsuggestion',
            name='subcategory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
