# Generated by Django 4.2.11 on 2024-07-21 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_productsuggestion_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsuggestion',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.subcategory'),
        ),
    ]
