# Generated by Django 4.2.11 on 2024-07-24 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_alter_productsuggestion_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyVisitedShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='backend.shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='backend.user')),
            ],
            options={
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'shop')},
            },
        ),
    ]
