vintage_thrift = Category.objects.create(name='Vintage & Thrift', parent=None)
thrift_stores = Category.objects.create(name='Thrift Stores', parent=vintage_thrift)
consignment_shops = Category.objects.create(name='Consignment Shops', parent=vintage_thrift)
vintage_clothing_stores = Category.objects.create(name='Vintage Clothing Stores', parent=vintage_thrift)
antique_shops = Category.objects.create(name='Antique Shops', parent=vintage_thrift)
second_hand_furniture = Category.objects.create(name='Second-Hand Furniture', parent=vintage_thrift)

vintage_thrift = Category.objects.get(name='Vintage & Thrift', parent=None)

thrift_stores = Category.objects.get(name='Thrift Stores', parent=vintage_thrift)
used_clothing = Category.objects.create(name='Used Clothing', parent=thrift_stores)
second_hand_books = Category.objects.create(name='Second-Hand Books', parent=thrift_stores)
used_furniture = Category.objects.create(name='Used Furniture', parent=thrift_stores)
vintage_accessories = Category.objects.create(name='Vintage Accessories', parent=thrift_stores)
pre_owned_electronics = Category.objects.create(name='Pre-Owned Electronics', parent=thrift_stores)

consignment_shops = Category.objects.get(name='Consignment Shops', parent=vintage_thrift)
designer_consignments = Category.objects.create(name='Designer Consignments', parent=consignment_shops)
furniture_consignments = Category.objects.create(name='Furniture Consignments', parent=consignment_shops)
art_and_collectibles_consignments = Category.objects.create(name='Art and Collectibles Consignments', parent=consignment_shops)
luxury_goods_consignments = Category.objects.create(name='Luxury Goods Consignments', parent=consignment_shops)

vintage_clothing_stores = Category.objects.get(name='Vintage Clothing Stores', parent=vintage_thrift)
retro_fashion = Category.objects.create(name='Retro Fashion', parent=vintage_clothing_stores)
antique_clothing = Category.objects.create(name='Antique Clothing', parent=vintage_clothing_stores)
vintage_accessories_clothing = Category.objects.create(name='Vintage Accessories', parent=vintage_clothing_stores)
vintage_costume_jewelry = Category.objects.create(name='Vintage Costume Jewelry', parent=vintage_clothing_stores)

antique_shops = Category.objects.get(name='Antique Shops', parent=vintage_thrift)
antique_furniture = Category.objects.create(name='Antique Furniture', parent=antique_shops)
antique_decor = Category.objects.create(name='Antique Decor', parent=antique_shops)
antique_collectibles = Category.objects.create(name='Antique Collectibles', parent=antique_shops)
vintage_art = Category.objects.create(name='Vintage Art', parent=antique_shops)

second_hand_furniture = Category.objects.get(name='Second-Hand Furniture', parent=vintage_thrift)
pre_owned_sofas = Category.objects.create(name='Pre-Owned Sofas', parent=second_hand_furniture)
used_dining_sets = Category.objects.create(name='Used Dining Sets', parent=second_hand_furniture)
second_hand_beds = Category.objects.create(name='Second-Hand Beds', parent=second_hand_furniture)
used_office_furniture = Category.objects.create(name='Used Office Furniture', parent=second_hand_furniture)
vintage_furniture_accessories = Category.objects.create(name='Vintage Furniture Accessories', parent=second_hand_furniture)
