luxury_designer = Category.objects.create(name='Luxury & Designer', parent=None)
designer_clothing = Category.objects.create(name='Designer Clothing', parent=luxury_designer)
luxury_jewelry = Category.objects.create(name='Luxury Jewelry', parent=luxury_designer)
high_end_watches = Category.objects.create(name='High-End Watches', parent=luxury_designer)
luxury_handbags = Category.objects.create(name='Luxury Handbags', parent=luxury_designer)
designer_shoes = Category.objects.create(name='Designer Shoes', parent=luxury_designer)
high_end_furniture = Category.objects.create(name='High-End Furniture', parent=luxury_designer)

designer_clothing = Category.objects.get(name='Designer Clothing')
menswear = Category.objects.create(name='Menswear', parent=designer_clothing)
womenswear = Category.objects.create(name='Womenswear', parent=designer_clothing)
couture = Category.objects.create(name='Couture', parent=designer_clothing)
bridal_wear = Category.objects.create(name='Bridal Wear', parent=designer_clothing)
evening_wear = Category.objects.create(name='Evening Wear', parent=designer_clothing)
designer_denim = Category.objects.create(name='Designer Denim', parent=designer_clothing)

luxury_jewelry = Category.objects.get(name='Luxury Jewelry')
fine_jewelry = Category.objects.create(name='Fine Jewelry', parent=luxury_jewelry)
statement_pieces = Category.objects.create(name='Statement Pieces', parent=luxury_jewelry)
custom_jewelry = Category.objects.create(name='Custom Jewelry', parent=luxury_jewelry)
engagement_rings = Category.objects.create(name='Engagement Rings', parent=luxury_jewelry)
luxury_bracelets = Category.objects.create(name='Luxury Bracelets', parent=luxury_jewelry)

high_end_watches = Category.objects.get(name='High-End Watches')
mechanical_watches = Category.objects.create(name='Mechanical Watches', parent=high_end_watches)
quartz_watches = Category.objects.create(name='Quartz Watches', parent=high_end_watches)
smart_watches = Category.objects.create(name='Smart Watches', parent=high_end_watches)
limited_edition_watches = Category.objects.create(name='Limited Edition Watches', parent=high_end_watches)
luxury_watch_straps = Category.objects.create(name='Luxury Watch Straps', parent=high_end_watches)

luxury_handbags = Category.objects.get(name='Luxury Handbags')
tote_bags = Category.objects.create(name='Tote Bags', parent=luxury_handbags)
clutch_bags = Category.objects.create(name='Clutch Bags', parent=luxury_handbags)
shoulder_bags = Category.objects.create(name='Shoulder Bags', parent=luxury_handbags)
backpacks = Category.objects.create(name='Backpacks', parent=luxury_handbags)
evening_bags = Category.objects.create(name='Evening Bags', parent=luxury_handbags)
travel_bags = Category.objects.create(name='Travel Bags', parent=luxury_handbags)

designer_shoes = Category.objects.get(name='Designer Shoes')
mens_designer_shoes = Category.objects.create(name='Men\'s Designer Shoes', parent=designer_shoes)
womens_designer_shoes = Category.objects.create(name='Women\'s Designer Shoes', parent=designer_shoes)
luxury_sneakers = Category.objects.create(name='Luxury Sneakers', parent=designer_shoes)
designer_heels = Category.objects.create(name='Designer Heels', parent=designer_shoes)
formal_shoes = Category.objects.create(name='Formal Shoes', parent=designer_shoes)
custom_shoes = Category.objects.create(name='Custom Shoes', parent=designer_shoes)

high_end_furniture = Category.objects.get(name='High-End Furniture')
designer_sofas = Category.objects.create(name='Designer Sofas', parent=high_end_furniture)
luxury_beds = Category.objects.create(name='Luxury Beds', parent=high_end_furniture)
designer_dining_sets = Category.objects.create(name='Designer Dining Sets', parent=high_end_furniture)
high_end_office_furniture = Category.objects.create(name='High-End Office Furniture', parent=high_end_furniture)
luxury_outdoor_furniture = Category.objects.create(name='Luxury Outdoor Furniture', parent=high_end_furniture)
custom_furniture = Category.objects.create(name='Custom Furniture', parent=high_end_furniture)