from ..models import Category


electronics = Category.objects.create(name='Electronics', parent=None)
furniture = Category.objects.create(name="Furniture", parent=None)
vehicles = Category.objects.create(name='Vehicles', parent=None)
property = Category.objects.create(name='Property', parent=None)
health_beauty = Category.objects.create(name='Health & Beauty')
fashion = Category.objects.create(name='Fashion', parent=None)
services = Category.objects.create(name='Services', parent=None)
babies = Category.objects.create(name="Babies & Kiddies", parent=None)
agriculture = Category.objects.create(name='Agriculture & Food', parent=None)
commercial_equipment = Category.objects.create(name='Commercial Equipments & Tools', parent=None)
pets = Category.objects.create(name='Pets', parent=None)
sports_arts = Category.objects.create(name='Sports, Arts & outdoors', parent=None)
repair_constructions = Category.objects.create(name='Repair & Constructions', parent=None)

books_stationery = Category.objects.create(name='Books & Stationery', parent=None)
toys_hobbies = Category.objects.create(name='Toys & Hobbies', parent=None)
luxury_designer = Category.objects.create(name='Luxury & Designer', parent=None)
green_eco_friendly = Category.objects.create(name='Green & Eco-friendly', parent=None)
party_event_supplies = Category.objects.create(name='Party & Event Supplies', parent=None)
vintage_thrift = Category.objects.create(name='Vintage & Thrift', parent=None)
office_school_supplies = Category.objects.create(name='Office & School Supplies', parent=None)
medical_healthcare = Category.objects.create(name='Medical & Healthcare', parent=None)
industrial_scientific = Category.objects.create(name='Industrial & Scientific', parent=None)
travel_luggage = Category.objects.create(name='Travel & Luggage', parent=None)
printing_publishing = Category.objects.create(name='Printing & Publishing', parent=None)
textiles_fabrics = Category.objects.create(name='Textiles & Fabrics', parent=None)
seasonal_holiday = Category.objects.create(name='Seasonal & Holiday', parent=None)
event_tickets = Category.objects.create(name='Event Tickets', parent=None)
spiritual_wellness = Category.objects.create(name='Spiritual & Wellness', parent=None)
rental_services = Category.objects.create(name='Rental Services', parent=None)
custom_personalized = Category.objects.create(name='Custom & Personalized', parent=None)
promotional_products = Category.objects.create(name='Promotional Products', parent=None)
grocery_supermarkets = Category.objects.create(name='Grocery & Supermarkets', parent=None)