books_stationery = Category.objects.create(name='Books & Stationery', parent=None)
bookstores = Category.objects.create(name='Bookstores', parent=books_stationery)
comic_book_shops = Category.objects.create(name='Comic Book Shops', parent=books_stationery)
stationery_stores = Category.objects.create(name='Stationery Stores', parent=books_stationery)
office_supplies = Category.objects.create(name='Office Supplies', parent=books_stationery)
art_supplies = Category.objects.create(name='Art Supplies', parent=books_stationery)

bookstores = Category.objects.create(name='Bookstores', parent=books_stationery)
fiction_books = Category.objects.create(name='Fiction Books', parent=bookstores)
non_fiction_books = Category.objects.create(name='Non-Fiction Books', parent=bookstores)
children_books = Category.objects.create(name='Children\'s Books', parent=bookstores)
academic_books = Category.objects.create(name='Academic Books', parent=bookstores)
self_help_books = Category.objects.create(name='Self-Help Books', parent=bookstores)
biographies = Category.objects.create(name='Biographies', parent=bookstores)
cookbooks = Category.objects.create(name='Cookbooks', parent=bookstores)
travel_guides = Category.objects.create(name='Travel Guides', parent=bookstores)
religious_books = Category.objects.create(name='Religious Books', parent=bookstores)
graphic_novels = Category.objects.create(name='Graphic Novels', parent=bookstores)

comic_book_shops = Category.objects.create(name='Comic Book Shops', parent=books_stationery)
superhero_comics = Category.objects.create(name='Superhero Comics', parent=comic_book_shops)
manga = Category.objects.create(name='Manga', parent=comic_book_shops)
graphic_novels_comics = Category.objects.create(name='Graphic Novels', parent=comic_book_shops)
indie_comics = Category.objects.create(name='Indie Comics', parent=comic_book_shops)
webcomics_print = Category.objects.create(name='Webcomics in Print', parent=comic_book_shops)

stationery_stores = Category.objects.create(name='Stationery Stores', parent=books_stationery)
writing_instruments = Category.objects.create(name='Writing Instruments', parent=stationery_stores)
notebooks = Category.objects.create(name='Notebooks', parent=stationery_stores)
calendars_planners = Category.objects.create(name='Calendars & Planners', parent=stationery_stores)
greeting_cards = Category.objects.create(name='Greeting Cards', parent=stationery_stores)
envelopes = Category.objects.create(name='Envelopes', parent=stationery_stores)
sticky_notes = Category.objects.create(name='Sticky Notes', parent=stationery_stores)
office_supplies_stationery = Category.objects.create(name='Office Supplies', parent=stationery_stores)

office_supplies = Category.objects.create(name='Office Supplies', parent=books_stationery)
printers_scanners = Category.objects.create(name='Printers & Scanners', parent=office_supplies)
office_furniture = Category.objects.create(name='Office Furniture', parent=office_supplies)
paper_products = Category.objects.create(name='Paper Products', parent=office_supplies)
filing_storage = Category.objects.create(name='Filing & Storage', parent=office_supplies)
writing_supplies = Category.objects.create(name='Writing Supplies', parent=office_supplies)
desk_organizers = Category.objects.create(name='Desk Organizers', parent=office_supplies)

art_supplies = Category.objects.create(name='Art Supplies', parent=books_stationery)
paints = Category.objects.create(name='Paints', parent=art_supplies)
brushes = Category.objects.create(name='Brushes', parent=art_supplies)
canvas_paper = Category.objects.create(name='Canvas & Paper', parent=art_supplies)
drawing_tools = Category.objects.create(name='Drawing Tools', parent=art_supplies)
sculpting_supplies = Category.objects.create(name='Sculpting Supplies', parent=art_supplies)
craft_supplies = Category.objects.create(name='Craft Supplies', parent=art_supplies)