party_event_supplies = Category.objects.create(name='Party & Event Supplies', parent=None)
party_supplies = Category.objects.create(name='Party Supplies', parent=party_event_supplies)
event_planning_services = Category.objects.create(name='Event Planning Services', parent=party_event_supplies)
balloon_shops = Category.objects.create(name='Balloon Shops', parent=party_event_supplies)
wedding_supplies = Category.objects.create(name='Wedding Supplies', parent=party_event_supplies)
florists = Category.objects.create(name='Florists', parent=party_event_supplies)
costume_shops = Category.objects.create(name='Costume Shops', parent=party_event_supplies)

party_event_supplies = Category.objects.get(name='Party & Event Supplies', parent=None)

party_supplies = Category.objects.get(name='Party Supplies', parent=party_event_supplies)
party_decorations = Category.objects.create(name='Party Decorations', parent=party_supplies)
tableware = Category.objects.create(name='Tableware', parent=party_supplies)
party_favors = Category.objects.create(name='Party Favors', parent=party_supplies)
party_invitations = Category.objects.create(name='Party Invitations', parent=party_supplies)
party_games = Category.objects.create(name='Party Games', parent=party_supplies)
themed_party_supplies = Category.objects.create(name='Themed Party Supplies', parent=party_supplies)

event_planning_services = Category.objects.get(name='Event Planning Services', parent=party_event_supplies)
wedding_planning = Category.objects.create(name='Wedding Planning', parent=event_planning_services)
corporate_event_planning = Category.objects.create(name='Corporate Event Planning', parent=event_planning_services)
birthday_party_planning = Category.objects.create(name='Birthday Party Planning', parent=event_planning_services)
festival_planning = Category.objects.create(name='Festival Planning', parent=event_planning_services)
conference_planning = Category.objects.create(name='Conference Planning', parent=event_planning_services)

balloon_shops = Category.objects.get(name='Balloon Shops', parent=party_event_supplies)
helium_balloons = Category.objects.create(name='Helium Balloons', parent=balloon_shops)
balloon_bouquets = Category.objects.create(name='Balloon Bouquets', parent=balloon_shops)
custom_balloons = Category.objects.create(name='Custom Balloons', parent=balloon_shops)
balloon_decorations = Category.objects.create(name='Balloon Decorations', parent=balloon_shops)

wedding_supplies = Category.objects.get(name='Wedding Supplies', parent=party_event_supplies)
wedding_decorations = Category.objects.create(name='Wedding Decorations', parent=wedding_supplies)
wedding_favors = Category.objects.create(name='Wedding Favors', parent=wedding_supplies)
wedding_invitations = Category.objects.create(name='Wedding Invitations', parent=wedding_supplies)
bridal_accessories = Category.objects.create(name='Bridal Accessories', parent=wedding_supplies)
wedding_flowers = Category.objects.create(name='Wedding Flowers', parent=wedding_supplies)

florists = Category.objects.get(name='Florists', parent=party_event_supplies)
flower_bouquets = Category.objects.create(name='Flower Bouquets', parent=florists)
floral_arrangements = Category.objects.create(name='Floral Arrangements', parent=florists)
wedding_flowers_florists = Category.objects.create(name='Wedding Flowers', parent=florists)
sympathy_flowers = Category.objects.create(name='Sympathy Flowers', parent=florists)
holiday_flowers = Category.objects.create(name='Holiday Flowers', parent=florists)

costume_shops = Category.objects.get(name='Costume Shops', parent=party_event_supplies)
halloween_costumes = Category.objects.create(name='Halloween Costumes', parent=costume_shops)
theater_costumes = Category.objects.create(name='Theater Costumes', parent=costume_shops)
costume_accessories = Category.objects.create(name='Costume Accessories', parent=costume_shops)
children_costumes = Category.objects.create(name='Children\'s Costumes', parent=costume_shops)
custom_costumes = Category.objects.create(name='Custom Costumes', parent=costume_shops)
